### ISSUE TITLE
v0.1.0 Release (Charlie)

### ISSUE THREAD

**Issue by romans127** [scorpiusjs/scorpius#6]
## v0.1.0 Punchlist

**Overview**
- [x] Update all packages to use api version `1.4.0.1`
- [x] Publish all packages to atmosphere under `Scorpius`

**Packages**
- [x] `new` scorpiusjs:legacy-scope
